### ISSUE TITLE
'Test Set Generation' allows me to create test data with x and y outside the model

### ISSUE THREAD

**Issue by markdouglasphd** [ITISFoundation/publication-IEC62209#16]
v1.0.12
When I enter the measurement area in 'Test Set Generation', the software should check it against the stored model.
So if the model has x_model = 100, y_model = 200, I should not be able to enter a measurement area of, say, x = 200, y = 500.

It should automatically correct the measurement area as follows:
x = max(80, min(x, x_model))
y = max(160, min(y, y_model))

**Comment by SCA-ZMT** [comment]
@odeimaiz I added '/test-set-generation/model-area' and '/search-space/model-area' GET operations to return a dictionary with `measAreaX` and `measAreaY` strings

**Comment by SCA-ZMT** [comment]
@markdouglasphd this issue is affected by the lack of data set metadata as you pointed out here: https://github.com/ITISFoundation/publication-IEC62209/issues/12

for now, we can only constrain the x and y to be within the training sample area, not the initial model domain area specified by the manufacturer
