### ISSUE TITLE
No output in case of perfect input

### ISSUE THREAD

**Issue by njain76** [ITISFoundation/publication-IEC62209#47]
[TrainingData_perfect.csv](https://github.com/ITISFoundation/publication-IEC62209/files/11413707/TrainingData_perfect.csv)

Hi,

For a perfect input (attached), ie... measured values equal to targets, the software does not give any output. In other words the 'Create and analyze' button does not do anything.

Regards,
Nitin

**Comment by SCA-ZMT** [comment]
@cbujard if it can be useful, I'm seeing the following exception: `AttributeError("'trf' is bounded and therefore not supported when all values are the same.")`

**Comment by cbujard** [comment]
Since all values are equal, there is no variance, a flat variogram at 0 where many computations don't work. This case has to be handled separately...

**Comment by cbujard** [comment]
@markdouglasphd 
Here is a suggestion: If the std dev of the computed sard values are strictly below 0.1, the software may automatically add white gaussian noise to the values. This will induce a non-zero (but small) flat variogram that will not break the process computations. In this case the tests should pass (we still need to test the magnitude of the noise) and the search algorithm will initiate a large number of trajectories, all of which will very likely fall below a 1% chance to violate the mpe.

**Comment by cbujard** [comment]
Hi @njain76 
Would you be able to send me your training sample with perfect input data? Thx. 
My bad sorry, you already posted this above. ^^

**Comment by cbujard** [comment]
I implemented my suggestion above. So if the user inputs a perfect sample as provided by Nitin, a tiny amount of noise is added. This allows the process to work as expected. In the end the critical points look like this: probability to pass mpe is 0. Note @SCA-ZMT  that NaN outputed values are possible (because of division by smth very small), so just make sure you are able to properly filter out NaN's. Ty. 

![fig6](https://github.com/ITISFoundation/publication-IEC62209/assets/118373269/80e0daa1-dae9-4159-ba72-64ea415f68f8)

![screen](https://github.com/ITISFoundation/publication-IEC62209/assets/118373269/93c06d33-b1e3-4896-9786-8e8064daa98f)
